"""tz

Revision ID: f82881fdf1ce
Revises: f8f36438d039
Create Date: 2026-08-07 13:06:29.035419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f82881fdf1ce'
down_revision: Union[str, Sequence[str], None] = 'f8f36438d039'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tz')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tz', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
